### ISSUE TITLE
Error ZeroDivisionError: division by zero in python 

### ISSUE THREAD

**Issue by Mahan-Asadi** [Mahan-Asadi/first-exercise-with-python#1]
When I open this Python program, I encounter this error. What is the solution?

**Comment by Mahan-Asadi** [comment]
This error occurs because we are trying to divide by zero, which is not allowed.
To resolve this error, we can use the try-except block in Python to handle such errors.

def divide_by_zero_safe():
    try:
        result = 10 / 0
        return result
    except ZeroDivisionError:
        print("Error: Division by zero occurred!")

result = divide_by_zero_safe()
if result is not None:
    print(result)

**Comment by Ms-moraveji1973** [comment]
This error occurs because we are trying to divide by zero, which is not allowed.
To resolve this error, we can use the try-except block in Python to handle such errors.

```python
def divide_by_zero_safe():
    try:
        result = 10 / 0
        return result
    except ZeroDivisionError:
        print("Error: Division by zero occurred!")

result = divide_by_zero_safe()
if result is not None:
    print(result)```

**Comment by Mahan-Asadi** [comment]
You're very welcome!, It's fixed.
